[package]
name = "sexpress"
version = "0.1.0"
authors = ["Vurich <jackefransham@gmail.com>"]

[dependencies]
toolshed = { git = "https://github.com/Vurich/toolshed.git", branch = "set-tools" }
smallvec = "*"

[features]
default = []
debug-output = []
benches = []
